booksnob/booksnob/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reader/', include('reader.urls')),
    url(r'^critic/', include('critic.urls')),
]

booksnob/critic/urls.py
from django.conf.urls import url
from critic.views import ReviewView, ThanksView

__author__ = 'Vladimir Volodavets'


urlpatterns = [
    url(r'^review/', ReviewView.as_view(), name='review-book'),
    url(r'^thanks/', ThanksView.as_view()),
]

booksnob/reader/urls.py
__author__ = 'Vladimir Volodavets'

from django.conf.urls import url
from reader import views

urlpatterns = [

    url(r'^$', views.HomeView.as_view()),

]

booksnob/critic/models.py
from django.db import models

# Create your models here.

booksnob/reader/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

    def __unicode__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)


class Book(models.Model):
    author = models.ForeignKey(Author)  # relationship 1:n
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return str(self.name)

booksnob/critic/forms.py
from django import forms
from critic.actions import get_books

__author__ = 'Vladimir Volodavets'


class ReviewForm(forms.Form):
    books = [
        (book, book) for book in get_books()
    ]
    book_name = forms.ChoiceField(choices=books)
    text = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        print('Book: {0}'.format(self.cleaned_data['book_name']))
        print('Message: {0}'.format(self.cleaned_data['text']))

booksnob/critic/views.py
from critic.forms import ReviewForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView


class ReviewView(FormView):
    template_name = 'bootstrap_review.html'
    form_class = ReviewForm
    success_url = '/critic/thanks/'

    def form_valid(self, form):
        form.send_email()
        return super(ReviewView, self).form_valid(form)


class ThanksView(TemplateView):
    template_name = 'thanks.html'

booksnob/reader/views.py
from django.views.generic import TemplateView
from reader.actions import get_books, get_authors


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['authors'] = get_authors()
        context['books'] = get_books()
        return context

booksnob/critic/templates/bootstrap_review.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
     <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
      {% load staticfiles %}
      <link href="{% static "critic/style.css" %}" rel="stylesheet">

  </head>
  <body>
    <div class="container">
         <header>
             <h1>Hello, this is a review page!</h1>
             <p>Select author</p>

             <form action="{% url 'review-book' %}" method="post">{% csrf_token %}

                <div align="center">
                     <select class="combobox" title="combo">
                         {% for val,txt in form.fields.book_name.choices %}
                         <option value="{{ val }}"> {{ txt }}</option>
                         {% endfor %}
                     </select>
                </div>

                <div align="center">
                    <textarea id="id_text" name="text"  title="text">{{ form.form.text }}</textarea>
                </div>

                <div align="center">
                    <input type="submit" class="btn btn-primary btn-lg" value="Send">
                </div>
             </form>

         </header>

    </div>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

booksnob/critic/templates/review.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form action="{% url 'review-book' %}" method="post">{% csrf_token %}
    <div>
    <label for="book_name">Book name: </label>
    <select id= "id_book_name" name="book_name" title="title">
    {% for val,txt in form.fields.book_name.choices %}
        <option value="{{ val }}"> {{ txt }}</option>
    {% endfor %}
    </select>

    </div>
    <div>
        <textarea id="id_text"
        name="text" >{{ form.form.text }}
        </textarea>
    </div>
    <div>
    <input type="submit" value="Send">
    </div>
</form>
</body>
</html>

booksnob/critic/templates/thanks.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
     {% load staticfiles %}
     <link href="{% static "critic/style.css" %}" rel="stylesheet">
    <title></title>
</head>
<body>
 <p>Thanks</p>

</body>
</html>

booksnob/reader/templates/home.html
Hi! <br>
{{ authors }} <br>
{{ books }}

booksnob/templates/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
    <link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <link href="../static/critic/style.css" rel="stylesheet">

  </head>
  <body>
    <div class="container">
         <header>
             <h1>Hello, this is a review page!</h1>
             <div class="dropdown">
                 <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                    Select Author
                 <span class="caret"></span>
                 </button>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                      {% for val,txt in form.fields.book_name.choices %}
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="#">{{ val }} - {{ txt }}</a></li>
                      {% endfor %}
                  </ul>
             </div>
</header>
    </div>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>